name: CyanchPlugin
version: 1.0
main: com.gmail.cyanthundermc.Cyanch1.CyanchPlugin
depend: [SQLiteLib]
loadbefore: [SQLiteLib]
commands:
  showhand:
    description: Reveals item in hand.
    usage: /showhand
  hiderain:
    description: Clears the Weather on the Player's End.
    usage: /hiderain
    aliases: [clearrain, clearweather]
  position:
    description: Tell everyone where you are!
    usage: /position
    aliases: [pos]
  map:
    description: Gives Dynmap Link.
    usage: /map
  serverworld:
    description: Switch between server worlds!
    usage: /serverworld <creative/survival>
  creative:
    description: Set of Creative Commands that can only be used in the Creative Server World!
    usage: /creative tp <target player> OR /creative tp <x> <y> <z> OR /creative gamemode <mode> OR /creative world <flat/void>